import * as React from "react"
import { Lock } from "lucide-react"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"

export function SystemTags() {
  const systemTags = [
    { name: "Area 1", color: "#1E293B" },
    { name: "Area 2", color: "#1E293B" },
    { name: "Area 3", color: "#1E293B" },
    { name: "Area 4", color: "#1E293B" },
    { name: "AY-2024-2025", color: "#64748B" },
    { name: "Approved", color: "#10B981" },
    { name: "Returned", color: "#EF4444" },
    { name: "Draft", color: "#94A3B8" },
  ]

  return (
    <div className="bg-white rounded-xl border border-slate-200 p-5 mb-6 shadow-sm">
      <div className="mb-4 flex flex-col gap-1">
        <div className="flex items-center gap-2">
          <h3 className="font-semibold text-slate-900">System Tags</h3>
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger>
                <Lock className="w-4 h-4 text-slate-400" />
              </TooltipTrigger>
              <TooltipContent>
                <p>Auto-generated by the system</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
        <p className="text-xs text-slate-500">
          These tags are automatically applied based on document metadata and status, and cannot be modified.
        </p>
      </div>

      <div className="bg-slate-50 rounded-lg p-4 flex flex-wrap gap-2 border border-slate-100">
        {systemTags.map((tag) => (
          <span
            key={tag.name}
            className="inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full cursor-not-allowed"
            style={{
              backgroundColor: `${tag.color}15`,
              color: tag.color,
              border: `1px solid ${tag.color}30`,
            }}
          >
            {tag.name}
            <Lock className="w-2.5 h-2.5" />
          </span>
        ))}
      </div>
    </div>
  )
}
